### ISSUE TITLE
I couldn't find a way to code 'for the loop' using your programming language

### ISSUE THREAD

**Issue by berkerugras** [berkinozturk/Turkish-Programming-Language#1]
Dear programmers, can you please give me some instructions about coding 'for loop'? I couldn't iterate the list that I've created. I didn't see any readme files inside your repo ;). Thanks.

**Comment by berkinozturk** [comment]
Hello Berker, the Turkish Programming Language we are creating is designed with grammar with delicate touches to reflect the naturalness of the language. In this project, on which we have been working very meticulously, arithmetic operations, assignment and if-else statements have been created, and we continue to work on other parts. Staying true to the critical path that we have planned, the loops of our programming language will be completed in a short time and a readme file will be created. Then you can come back and try :)
